# Generated by Django 6.0 on 2025-12-14 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Istasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(choices=[('BA', 'Başiskele'), ('CA', 'Çayırova'), ('DA', 'Darıca'), ('DE', 'Derince'), ('DI', 'Dilovası'), ('GE', 'Gebze'), ('GO', 'Gölcük'), ('KA', 'Kandıra'), ('KM', 'Karamürsel'), ('KT', 'Kartepe'), ('KO', 'Körfez'), ('IZ', 'İzmit')], max_length=50, unique=True, verbose_name='İlçe/İstasyon Adı')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
            ],
            options={
                'verbose_name_plural': 'İstasyonlar',
            },
        ),
        migrations.CreateModel(
            name='KargoAraci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=10, unique=True, verbose_name='Araç Plakası')),
                ('kapasite_kg', models.IntegerField(verbose_name='Kargo Kapasitesi (kg)')),
                ('kiralama_maliyeti', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kiralama Maliyeti (Birim)')),
                ('yakit_tuketimi_km_basina', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Yol Maliyeti (km başına)')),
            ],
            options={
                'verbose_name_plural': 'Kargo Araçları',
            },
        ),
        migrations.CreateModel(
            name='Kargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agirlik_kg', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('adet', models.IntegerField(verbose_name='Kargo Adedi')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('rotaya_atanmis', models.BooleanField(default=False, verbose_name='Rotaya Atandı mı?')),
                ('gonderen_kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen Kullanıcı')),
                ('kaynak_istasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giden_kargolar', to='kargo.istasyon', verbose_name='Kaynak İstasyon')),
            ],
            options={
                'verbose_name_plural': 'Kargolar',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sefer_tarihi', models.DateField(auto_now_add=True, verbose_name='Sefer Tarihi')),
                ('toplam_mesafe_km', models.FloatField(default=0, verbose_name='Toplam Mesafe (km)')),
                ('toplam_maliyet', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Maliyet (Kira + Yol)')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kargo.kargoaraci', verbose_name='Atanan Araç')),
            ],
            options={
                'verbose_name_plural': 'Rotasyonlar',
            },
        ),
        migrations.CreateModel(
            name='RotaDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ziyaret_sirasi', models.IntegerField(verbose_name='Ziyaret Sırası')),
                ('istasyon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kargo.istasyon', verbose_name='Ziyaret Edilecek İstasyon')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detaylar', to='kargo.rota')),
            ],
            options={
                'verbose_name_plural': 'Rota Detayları',
                'ordering': ['ziyaret_sirasi'],
            },
        ),
    ]
