# Generated by Django 6.0 on 2025-12-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rota',
            options={'verbose_name': 'Rota', 'verbose_name_plural': 'Rotas'},
        ),
        migrations.RenameField(
            model_name='kargoaraci',
            old_name='yakit_tuketimi_km_basina',
            new_name='yakit_tuketimi_km_basi',
        ),
        migrations.AddField(
            model_name='rota',
            name='yakit_tuketimi_km_basi',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Araç Yakıt Tüketimi (km/birim)'),
        ),
    ]
