# Generated by Django 6.0 on 2025-12-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0002_alter_rota_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='toplam_maliyet',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='yakit_tuketimi_km_basi',
        ),
    ]
