# Generated by Django 6.0 on 2025-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0003_remove_rota_toplam_maliyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='toplam_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Maliyet (Kira + Yol)'),
        ),
    ]
