# Generated by Django 6.0 on 2025-12-26 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0004_rota_toplam_maliyet'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargo',
            name='rota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasinan_kargolar', to='kargo.rota', verbose_name='Atanan Rota'),
        ),
    ]
