# Generated by Django 6.0 on 2025-12-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0005_kargo_rota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kargo',
            name='rota',
            field=models.ForeignKey(blank=True, help_text='Otomatik atanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasinan_kargolar', to='kargo.rota', verbose_name='Atanan Rota'),
        ),
    ]
